#!/usr/bin/env python3
"""Generate the Plan-06 disk-I/O subset steps file + manifest.

Subset to validate the disk-I/O channel: 8 workloads x 600 s x 2 reps = 16 cells,
covering both threat families (4 ransomware + scanner) and the masquerade benigns
(pagefault, mmap, workingset). Reuses the LOCKED v3 flags from Plan 05's generator
(no flag drift). Each step also carries --duration 600 + --phase-markers and, for
file-writing workloads, the --sandbox-dir/--backing-dir scratch redirect.

Emits:
  diskio_subset_steps.txt     -- the 16 command lines (STEPS_FILE for the run)
  diskio_subset_manifest.csv  -- step_index,test_name,workload,duration_s,rep,
                                 traj_file  (apf trajectory; the .diskio_trajectory
                                 sibling is derived by build_cells_dir)

    python3 plan06_campaign/generate_diskio_subset.py
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
P5 = HERE.parent / "plan05_campaign"
sys.path.insert(0, str(P5))
from generate_full_steps import BIN, SCRATCH, WORKLOADS, safe_label  # noqa: E402

SUBSET = [
    "sandbox_ransom_slowburn", "sandbox_ransom_batched",
    "sandbox_ransom_selective", "sandbox_ransom_seq",
    "sandbox_scanner_metadata",
    "mem_pagefault_density_v2", "mem_mmap_traversal_v2",
    "mem_workingset_sweep_v2",
]
DURATIONS = [600]
REPS = [1, 2]
SPEC = {b: (flags, sf) for (b, flags, sf) in WORKLOADS}


def main() -> int:
    steps, rows, i = [], [], 0
    for rep in REPS:
        for dur in DURATIONS:
            for binary in SUBSET:
                flags, scratch_flag = SPEC[binary]
                i += 1
                scratch = f" {scratch_flag} {SCRATCH}" if scratch_flag else ""
                steps.append(f"{BIN}/{binary} {flags}{scratch} "
                             f"--duration {dur} --phase-markers")
                tn = f"test{i}_{safe_label(binary)}"
                rows.append({
                    "step_index": i, "test_name": tn, "workload": binary,
                    "duration_s": dur, "rep": rep,
                    "traj_file": f"run_matrix_{tn}.npy.apf_trajectory.jsonl",
                })

    header = (
        "# Plan 06 -- disk-I/O subset (8 workloads x 600s x 2 reps = 16 cells).\n"
        "# GENERATED by generate_diskio_subset.py; reuses Plan 05's locked flags.\n"
        "# Launch (server, inside screen), with the NEW disk-I/O flag on:\n"
        "#   CAPTURE_MODE=1 CAPTURE_METRIC=apf_queue SUSTAIN_LOOP=1 CAPTURE_DISKIO=1 \\\n"
        "#     SSH_TARGET=kali@192.168.222.63 SSH_KEY=/project/homes/jeries/.ssh/id_ed25519 \\\n"
        "#     CONFIG=config_qemu_upc.json STEPS_FILE=plan06_campaign/diskio_subset_steps.txt \\\n"
        "#     python3 -u run_files_controlled.py 2>&1 | tee plan06_campaign/diskio_subset.log\n"
    )
    (HERE / "diskio_subset_steps.txt").write_text(header + "\n".join(steps) + "\n")
    with (HERE / "diskio_subset_manifest.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    assert len(steps) == len(SUBSET) * len(DURATIONS) * len(REPS) == 16
    print(f"wrote diskio_subset_steps.txt ({len(steps)} steps)")
    print(f"wrote diskio_subset_manifest.csv ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
