#!/usr/bin/env python3
"""Console bridge -- localhost server that lets the Capture Console UI plan,
preflight, launch, monitor, and stop captures ON THE SERVER it runs on.

Runs where run_files_controlled.py runs (the QEMU host). The browser reaches it
over an SSH tunnel:

    server$  python3 ui/console_bridge.py --port 8000
    laptop$  ssh -L 8000:localhost:8000 user@server
    laptop   open http://localhost:8000/?token=<printed-on-server-stdout>

SECURITY (see ui/README.md):
  * Binds 127.0.0.1 ONLY -- never network-exposed; reachable solely via the
    user's own SSH tunnel.
  * Jupyter-style token: printed to stdout on startup, required in the GET /
    URL (`/?token=...`) and in the X-Console-Token header on every API call.
    On a shared host any co-resident process can hit 127.0.0.1:port, so the
    token (which only the operator's terminal shows) is what gates access --
    GET / without it returns 403 and never leaks the token.
  * Trusted re-derivation: the UI sends structured intent (config + per-cell
    curation), NEVER raw commands. Guest commands are regenerated by
    subset_run.py from full_campaign_steps.txt, so nothing arbitrary reaches
    the guest. The launch line is built by subset_run.py's own env functions,
    so only known env keys can appear; UI-supplied host values (ssh target/key,
    zstd dir) are shlex-quoted by subset_run before they enter the line.
  * Namespaced screens: mem_console_<label>. /status and /stop only ever touch
    mem_console_* sessions.
  * The SSH key never touches the bridge process -- run_files_controlled.py uses
    it on the server exactly as today.

stdlib only.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shlex
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse, parse_qs

HERE = Path(__file__).resolve().parent               # .../plan07_campaign/ui
CAMPAIGN = HERE.parent                                # .../plan07_campaign
QEMU_DIR = CAMPAIGN.parent                            # .../VM_Capture_QEMU
SUBSET_RUN = CAMPAIGN / "subset_run.py"
PREFLIGHT = QEMU_DIR / "qa" / "preflight.sh"
RUNS = CAMPAIGN / "runs"
CONFIGS = CAMPAIGN / "configs"                        # saved (not-yet-launched) plans
CAPTURE_CONFIG = QEMU_DIR / "config_qemu_upc.json"    # imageDir / queueDir live here
SERVED_HTML = HERE / "capture_console.served.html"
VM_DOMAIN = os.environ.get("VM_DOMAIN", "Kali Jeries")
VIRSH_URI = os.environ.get("VIRSH_URI", "qemu:///system")
MIN_FREE_DISK_GB = 40

LABEL_RE = re.compile(r"^[A-Za-z0-9_-]+$")            # same as subset_run.py
SCREEN_PREFIX = "mem_console_"
PRODUCER_SCRIPTS = ("capture_producer_qemu_pmemsave.sh", "capture_producer_qemu.sh")
CONSUMER_SCRIPT = "capture_consumer_qemu.sh"

TOKEN = ""            # set in main()
PORT = 0              # set in main()


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _valid_label(label: str) -> bool:
    return isinstance(label, str) and bool(LABEL_RE.match(label))


def _write_tmp(text: str, suffix: str) -> Path:
    fd, name = tempfile.mkstemp(suffix=suffix, prefix="console_", dir=str(RUNS / ".staging"))
    p = Path(name)
    with os.fdopen(fd, "w") as fh:
        fh.write(text)
    return p


def _run(argv: list[str], cwd: Path, env: dict | None = None, timeout: int = 120):
    """subprocess.run wrapper returning (rc, stdout, stderr)."""
    r = subprocess.run(argv, cwd=str(cwd), env=env, capture_output=True,
                       text=True, timeout=timeout)
    return r.returncode, r.stdout, r.stderr


def _subset_run(config: dict, seed: int, *, print_cells: bool = False,
                curation: list | None = None, out: Path | None = None,
                runs_dir: Path | None = None, ssh_target: str | None = None,
                ssh_key: str | None = None, zstd_dir: str | None = None):
    """Invoke subset_run.py as a subprocess. Returns (rc, stdout, stderr).

    Config/curation are passed as temp JSON files. subset_run.py is the single
    trusted generator: it validates, re-derives the guest commands, and (for the
    write path) composes the launch line from known env functions only.
    """
    cfg_path = _write_tmp(json.dumps(config), ".config.json")
    argv = [sys.executable, str(SUBSET_RUN), "--config", str(cfg_path), "--seed", str(seed)]
    cur_path = None
    if print_cells:
        argv.append("--print-cells")
    else:
        argv += ["--out", str(out), "--runs-dir", str(runs_dir)]
        if ssh_target:
            argv += ["--ssh-target", ssh_target]
        if ssh_key:
            argv += ["--ssh-key", ssh_key]
        if zstd_dir:
            argv += ["--zstd-dir", zstd_dir]
        if curation is not None:
            cur_path = _write_tmp(json.dumps(curation), ".curation.json")
            argv += ["--curation", str(cur_path)]
    try:
        return _run(argv, cwd=CAMPAIGN, timeout=120)
    finally:
        cfg_path.unlink(missing_ok=True)
        if cur_path:
            cur_path.unlink(missing_ok=True)


def _screens() -> list[str]:
    """Active screen sessions named mem_console_*. `screen -ls` exits 1 when
    sessions exist, so ignore rc and parse stdout."""
    try:
        r = subprocess.run(["screen", "-ls"], capture_output=True, text=True, timeout=10)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    out = []
    for line in r.stdout.splitlines():
        m = re.search(r"\b(\d+\." + re.escape(SCREEN_PREFIX) + r"[A-Za-z0-9_-]+)", line)
        if m:
            out.append(m.group(1))
    return out


# --------------------------------------------------------------------------- #
# endpoint logic (each returns (status_code, obj))
# --------------------------------------------------------------------------- #
def ep_plan(body: dict):
    cfg = body.get("config")
    seed = int(body.get("seed", 42))
    if not isinstance(cfg, dict):
        return 400, {"error": "missing config object"}
    rc, out, err = _subset_run(cfg, seed, print_cells=True)
    if rc != 0:
        return 400, {"error": "subset_run rejected the config", "detail": err.strip()}
    try:
        return 200, json.loads(out)
    except json.JSONDecodeError:
        return 500, {"error": "could not parse cells", "detail": out[:2000]}


def ep_preflight(body: dict):
    cfg = body.get("config")
    seed = int(body.get("seed", 42))
    curation = body.get("curation")
    ssh_target = body.get("ssh_target")
    ssh_key = body.get("ssh_key")
    zstd_dir = body.get("zstd_dir")
    smoke = bool(body.get("smoke"))
    if not isinstance(cfg, dict):
        return 400, {"error": "missing config object"}
    label = cfg.get("label", "")
    if not _valid_label(label):
        return 400, {"error": f"invalid label {label!r}"}

    # Generate the curated steps into a throwaway staging area (no permanent
    # runs/<label>.json yet -- that is created only on real launch, so preflight
    # can be re-run freely and the collision guard fires at launch, not here).
    staging = Path(tempfile.mkdtemp(prefix=f"pf_{label}_", dir=str(RUNS / ".staging")))
    try:
        steps = staging / f"{label}_steps.txt"
        rc, out, err = _subset_run(cfg, seed, curation=curation, out=steps,
                                   runs_dir=staging, ssh_target=ssh_target,
                                   ssh_key=ssh_key, zstd_dir=zstd_dir)
        if rc != 0:
            return 400, {"error": "generation failed", "detail": err.strip() or out.strip()}
        meta = json.loads((staging / f"{label}.json").read_text())

        # preflight.sh reads env; --json writes a machine verdict.
        report = staging / "preflight.json"
        env = os.environ.copy()
        if ssh_target:
            env["SSH_TARGET"] = ssh_target
        if ssh_key:
            env["SSH_KEY"] = ssh_key
        if zstd_dir:
            env["ZSTD_DIR"] = zstd_dir
        argv = ["bash", str(PREFLIGHT), "--steps", str(steps), "--json", str(report)]
        if smoke:
            argv.append("--smoke")
        try:
            prc, pout, perr = _run(argv, cwd=QEMU_DIR, env=env, timeout=900)
        except subprocess.TimeoutExpired:
            return 504, {"error": "preflight timed out"}
        verdict = None
        if report.exists():
            try:
                verdict = json.loads(report.read_text())
            except json.JSONDecodeError:
                pass
        return 200, {
            "ok": prc == 0,
            "exit": prc,
            "cells": meta["cells"],
            "launch_line": meta["launch_line"],
            "preflight": verdict,
            "preflight_stdout": pout[-4000:],
        }
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def ep_launch(body: dict):
    cfg = body.get("config")
    seed = int(body.get("seed", 42))
    curation = body.get("curation")
    ssh_target = body.get("ssh_target")
    ssh_key = body.get("ssh_key")
    zstd_dir = body.get("zstd_dir")
    if not isinstance(cfg, dict):
        return 400, {"error": "missing config object"}
    label = cfg.get("label", "")
    if not _valid_label(label):
        return 400, {"error": f"invalid label {label!r}"}

    if f"{SCREEN_PREFIX}{label}" in " ".join(_screens()):
        return 409, {"error": f"a screen for {label!r} is already running"}

    # Real generation: writes runs/<label>_steps.txt + runs/<label>.json (the
    # collision guard in subset_run.py refuses a duplicate label here).
    steps = RUNS / f"{label}_steps.txt"
    rc, out, err = _subset_run(cfg, seed, curation=curation, out=steps,
                               runs_dir=RUNS, ssh_target=ssh_target,
                               ssh_key=ssh_key, zstd_dir=zstd_dir)
    if rc != 0:
        return 400, {"error": "generation failed", "detail": err.strip() or out.strip()}
    meta = json.loads((RUNS / f"{label}.json").read_text())
    launch_line = meta["launch_line"]

    # Launch in a detached screen, teeing the orchestrator's output to a log the
    # monitor tails. launch_line is fully composed + internally shlex-quoted by
    # subset_run.py; the wrapping script is built with shlex.quote for the paths,
    # and passed to screen via an argv list (no shell=True), so nothing the UI
    # supplied can break out.
    log_path = RUNS / f"{label}.log"
    session = f"{SCREEN_PREFIX}{label}"
    script = (f"cd {shlex.quote(str(QEMU_DIR))} && "
              f"{launch_line} 2>&1 | tee {shlex.quote(str(log_path))}")
    try:
        src, sout, serr = _run(["screen", "-dmS", session, "bash", "-c", script],
                               cwd=QEMU_DIR, timeout=30)
    except FileNotFoundError:
        return 500, {"error": "screen is not installed on the server"}
    if src != 0:
        return 500, {"error": "screen failed to start", "detail": serr.strip()}
    return 200, {"screen": session, "log": str(log_path), "launch_line": launch_line,
                 "cells": meta["cells"]}


def ep_status(_query: dict):
    sessions = _screens()
    runs = []
    for s in sessions:
        label = s.split(SCREEN_PREFIX, 1)[1]
        log = RUNS / f"{label}.log"
        tail = ""
        if log.exists():
            data = log.read_text(errors="replace")
            tail = data[-2000:]
        runs.append({"label": label, "screen": s, "log": str(log),
                     "log_size": log.stat().st_size if log.exists() else 0, "tail": tail})
    return 200, {"running": runs}


def ep_log(query: dict):
    label = (query.get("label") or [""])[0]
    offset = int((query.get("offset") or ["0"])[0])
    if not _valid_label(label):
        return 400, {"error": "invalid label"}
    log = RUNS / f"{label}.log"           # only ever this run's own log
    if not log.exists():
        return 200, {"offset": 0, "data": "", "eof": True}
    size = log.stat().st_size
    if offset > size:                     # log rotated/shrank -> restart
        offset = 0
    with log.open("r", errors="replace") as fh:
        fh.seek(offset)
        data = fh.read()
    running = f"{SCREEN_PREFIX}{label}" in " ".join(_screens())
    return 200, {"offset": offset + len(data.encode("utf-8", "replace")),
                 "data": data, "eof": not running}


def ep_stop(body: dict):
    label = body.get("label", "")
    if not _valid_label(label):
        return 400, {"error": "invalid label"}
    session = f"{SCREEN_PREFIX}{label}"
    if session not in " ".join(_screens()):
        return 404, {"error": f"no running screen for {label!r}"}
    # Quit the screen (stops the foreground orchestrator between SSH steps).
    _run(["screen", "-S", session, "-X", "quit"], cwd=QEMU_DIR, timeout=15)
    # Best-effort teardown of the nohup'd producer/consumer for the current step.
    # pkill -f is process-NAME-global; on this single-VM/single-user host that is
    # the intended blast radius, but it is why stop is "best effort".
    killed = []
    for script in (*PRODUCER_SCRIPTS, CONSUMER_SCRIPT):
        rc, _o, _e = _run(["pkill", "-f", script], cwd=QEMU_DIR, timeout=15)
        if rc == 0:
            killed.append(script)
    return 200, {"stopped": session, "killed": killed,
                 "warning": "Stop is best-effort. If a capture was mid-step, check the "
                            "VM state (virsh list --all / virsh domstate) and for leftover "
                            "guest scratch before the next launch."}


def ep_save(body: dict):
    """Persist a not-yet-launched plan to configs/<label>.json. The file is a
    valid subset config (subset_run.py can run it directly), plus UI-restore
    metadata under underscore keys that subset_run ignores. Overwrite is allowed
    -- a saved plan is a draft you refine, unlike a launched runid.
    """
    cfg = body.get("config")
    if not isinstance(cfg, dict):
        return 400, {"error": "missing config object"}
    label = cfg.get("label", "")
    if not _valid_label(label):
        return 400, {"error": f"invalid label {label!r}"}
    CONFIGS.mkdir(parents=True, exist_ok=True)
    saved = dict(cfg)  # the launchable config
    saved["_saved_at"] = datetime.now(timezone.utc).isoformat()
    saved["_seed"] = int(body.get("seed", 42))
    if body.get("curation") is not None:
        saved["_curation"] = body["curation"]
    path = CONFIGS / f"{label}.json"
    path.write_text(json.dumps(saved, indent=2) + "\n")
    return 200, {"saved": str(path), "label": label}


def ep_saved(_query: dict):
    """List saved plans in configs/ with enough to repopulate the UI."""
    if not CONFIGS.is_dir():
        return 200, {"plans": []}
    plans = []
    for p in sorted(CONFIGS.glob("*.json")):
        try:
            d = json.loads(p.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        plans.append({
            "label": d.get("label", p.stem),
            "saved_at": d.get("_saved_at"),
            "seed": d.get("_seed", 42),
            "retention": d.get("retention"),
            "capture_metric": d.get("capture_metric"),
            "config": {k: v for k, v in d.items() if not k.startswith("_")},
            "curation": d.get("_curation"),
        })
    plans.sort(key=lambda x: x.get("saved_at") or "", reverse=True)
    return 200, {"plans": plans}


def ep_delete_saved(body: dict):
    label = body.get("label", "")
    if not _valid_label(label):
        return 400, {"error": "invalid label"}
    path = CONFIGS / f"{label}.json"   # only ever a file in configs/, named by a safe label
    if path.exists():
        path.unlink()
        return 200, {"deleted": label}
    return 404, {"error": f"no saved plan {label!r}"}


CLEANUP_SCRIPT = QEMU_DIR / "cleanup_qemu_capture.sh"
GUEST_SCRATCH = "/var/tmp/phase2_campaign"   # the guest scratch root every workload writes under


def ep_clean_host(_body: dict):
    """Run the existing cleanup_qemu_capture.sh: kill stray producer/consumer,
    clear the job queues, and delete leftover memory_dump* files. This is exactly
    the host-side residue preflight flags (strays, queue/processing, leftover raw
    dumps). It does NOT touch the retention tree or runs/ metadata.
    """
    if not CLEANUP_SCRIPT.exists():
        return 404, {"error": f"cleanup script not found at {CLEANUP_SCRIPT}"}
    try:
        rc, out, err = _run(["bash", str(CLEANUP_SCRIPT)], cwd=QEMU_DIR, timeout=120)
    except subprocess.TimeoutExpired:
        return 504, {"error": "host cleanup timed out"}
    return 200, {"ok": rc == 0, "exit": rc, "output": (out + err)[-4000:]}


def ep_clean_guest(body: dict):
    """Clear the guest scratch dir over SSH. The path is FIXED (GUEST_SCRATCH),
    never taken from the request, so nothing arbitrary is deleted; only the ssh
    target/key are supplied. The orchestrator reclaims scratch per-cell anyway --
    this is the manual/pre-run equivalent for leftover-from-a-crash residue.
    """
    ssh_target = body.get("ssh_target")
    ssh_key = body.get("ssh_key")
    if not ssh_target:
        return 400, {"error": "ssh_target (the guest, e.g. kali@...) is required"}
    argv = ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=8"]
    if ssh_key:
        argv += ["-i", ssh_key]
    remote = (f"rm -rf {shlex.quote(GUEST_SCRATCH)}/* 2>/dev/null; "
              f"echo -n 'remaining: '; du -sh {shlex.quote(GUEST_SCRATCH)} 2>/dev/null || echo '(empty)'")
    argv += [ssh_target, remote]
    try:
        rc, out, err = _run(argv, cwd=QEMU_DIR, timeout=40)
    except subprocess.TimeoutExpired:
        return 504, {"error": "guest cleanup timed out (guest reachable?)"}
    return 200, {"ok": rc == 0, "exit": rc, "output": (out + err).strip()[-2000:]}


def _disk_free_gb(path: str):
    try:
        return shutil.disk_usage(path).free / (1024 ** 3)
    except Exception:
        return None


def ep_health(body: dict):
    """Runtime health of a capture in progress: is it safe to keep running, or
    should you stop? Basic checks always; deeper ones only when deep=True.
    Returns findings [{section, level, message}] in the same shape the UI renders
    the preflight report with.
    """
    deep = bool(body.get("deep"))
    zstd_dir = body.get("zstd_dir")
    cfg = {}
    try:
        cfg = json.loads(CAPTURE_CONFIG.read_text())
    except Exception:
        pass
    image_dir = cfg.get("imageDir")
    queue_dir = cfg.get("queueDir")
    F = []
    def add(section, level, message): F.append({"section": section, "level": level, "message": message})

    # --- disk: the run stops (or corrupts) if imageDir / ZSTD_DIR fill ---
    for name, p in [("imageDir", image_dir), ("ZSTD_DIR", zstd_dir)]:
        if not p:
            continue
        g = _disk_free_gb(p)
        if g is None:
            add("Disk", "warn", f"{name} {p}: can't read free space")
        elif g < MIN_FREE_DISK_GB:
            add("Disk", "fail", f"{name}: {g:.0f} GiB free (below {MIN_FREE_DISK_GB} GiB — the run will halt itself)")
        elif g < 2 * MIN_FREE_DISK_GB:
            add("Disk", "warn", f"{name}: {g:.0f} GiB free (getting low)")
        else:
            add("Disk", "ok", f"{name}: {g:.0f} GiB free")

    # --- producer/consumer alive while a capture screen is up ---
    screens = _screens()
    running = bool(screens)
    for name, pat in [("producer", "capture_producer"), ("consumer", "capture_consumer_qemu.sh")]:
        alive = _run(["pgrep", "-f", pat], cwd=QEMU_DIR, timeout=10)[0] == 0
        if running and not alive:
            add("Processes", "fail", f"{name} not running while a capture is active — captures will stall")
        else:
            add("Processes", "ok", f"{name} {'running' if alive else 'idle (no active capture)'}")

    # --- queue: backed-up processing / any failed = trouble ---
    if queue_dir:
        for sub in ("pending", "processing", "failed"):
            d = Path(queue_dir) / sub
            n = len(list(d.glob("*"))) if d.is_dir() else 0
            lvl = "fail" if (sub == "failed" and n) else ("warn" if (sub == "processing" and n > 4) else "ok")
            add("Queue", lvl, f"queue/{sub}: {n} job(s)")

    # --- leftover dumps piling up = consumer falling behind / not cleaning ---
    if image_dir and Path(image_dir).is_dir():
        nd = len(list(Path(image_dir).glob("memory_dump*")))
        add("Cleanup", "warn" if nd > 50 else "ok",
            f"{nd} raw dump(s) in imageDir" + (" — consumer may be behind" if nd > 50 else ""))

    # --- VM state ---
    st = _run(["virsh", "-c", VIRSH_URI, "domstate", VM_DOMAIN], cwd=QEMU_DIR, timeout=10)[1].strip()
    add("VM", "ok" if st == "running" else ("warn" if st == "paused" else "fail"),
        f"domain '{VM_DOMAIN}': {st or 'unknown'}")
    add("Run", "ok" if running else "warn",
        (", ".join(screens)) if running else "no capture screen active")

    if deep:
        ssh_target, ssh_key = body.get("ssh_target"), body.get("ssh_key")
        if ssh_target:
            argv = ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=8"]
            if ssh_key:
                argv += ["-i", ssh_key]
            argv += [ssh_target, f"du -sh {shlex.quote(GUEST_SCRATCH)} 2>/dev/null || echo '(empty)'"]
            rc, out, _e = _run(argv, cwd=QEMU_DIR, timeout=30)
            add("Guest (deep)", "ok" if rc == 0 else "warn", f"guest scratch: {out.strip() or 'unreachable'}")
        if zstd_dir and Path(zstd_dir).is_dir():
            chains = sum(1 for _ in Path(zstd_dir).rglob("*.zst"))
            add("Retention (deep)", "ok", f"{chains} compressed chain file(s) written under ZSTD_DIR")

    return 200, {
        "findings": F,
        "passed": sum(1 for f in F if f["level"] == "ok"),
        "warnings": sum(1 for f in F if f["level"] == "warn"),
        "failures": sum(1 for f in F if f["level"] == "fail"),
        "ok": not any(f["level"] == "fail" for f in F),
    }


def ep_run_status(query: dict):
    """Per-step status of a run, parsed from its log: ok / fail / running /
    skipped / pending, one row per workload (same list shape as preflight)."""
    label = (query.get("label") or [""])[0]
    if not _valid_label(label):
        return 400, {"error": "invalid label"}
    steps_file = RUNS / f"{label}_steps.txt"
    log = RUNS / f"{label}.log"
    total = 0
    if steps_file.exists():
        total = len([l for l in steps_file.read_text().splitlines() if l.strip()])
    steps = {}
    if log.exists():
        cur = None
        for line in log.read_text(errors="replace").splitlines():
            m = re.search(r"=====\s*Step (\d+)/(\d+)\s*:\s*(\S+)", line)
            if m:
                cur = int(m.group(1)); total = max(total, int(m.group(2)))
                wl = re.sub(r"^test\d+_", "", m.group(3))
                steps[cur] = {"i": cur, "workload": wl, "status": "running", "detail": ""}
                continue
            if cur is None:
                continue
            if "completed successfully" in line:
                steps[cur]["status"] = "ok"
            elif "Workload exit code:" in line:
                mm = re.search(r"exit code:\s*(\d+)", line)
                steps[cur]["status"] = "fail"; steps[cur]["detail"] = f"exit {mm.group(1) if mm else '?'}"
            elif "255 (CONNECTION FAILURE" in line or "still 255" in line:
                steps[cur]["status"] = "fail"; steps[cur]["detail"] = "ssh 255"
            elif "skipping step" in line or "would not start" in line:
                steps[cur]["status"] = "skipped"
    out = [steps.get(i, {"i": i, "workload": "(pending)", "status": "pending", "detail": ""})
           for i in range(1, total + 1)]
    done = sum(1 for s in out if s["status"] in ("ok", "fail", "skipped"))
    return 200, {"label": label, "total": total, "done": done, "steps": out,
                 "running": f"{SCREEN_PREFIX}{label}" in " ".join(_screens())}


ROUTES_POST = {"/plan": ep_plan, "/preflight": ep_preflight,
               "/launch": ep_launch, "/stop": ep_stop,
               "/save": ep_save, "/delete_saved": ep_delete_saved,
               "/clean_host": ep_clean_host, "/clean_guest": ep_clean_guest,
               "/health": ep_health}
ROUTES_GET = {"/status": ep_status, "/log": ep_log, "/saved": ep_saved,
              "/run_status": ep_run_status}


# --------------------------------------------------------------------------- #
# HTTP handler
# --------------------------------------------------------------------------- #
class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass  # quiet; we print our own concise line below

    def _send(self, code: int, obj, content_type="application/json"):
        if content_type == "application/json":
            payload = json.dumps(obj).encode()
        else:
            payload = obj if isinstance(obj, bytes) else obj.encode()
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        # localhost + tunnel only; no CORS (same-origin from the served page).
        self.end_headers()
        self.wfile.write(payload)

    def _token_ok_header(self) -> bool:
        return secrets.compare_digest(self.headers.get("X-Console-Token", ""), TOKEN)

    def do_GET(self):
        u = urlparse(self.path)
        if u.path == "/" or u.path == "/index.html":
            q = parse_qs(u.query)
            tok = (q.get("token") or [""])[0]
            if not secrets.compare_digest(tok, TOKEN):
                self._send(403, "Forbidden: open the URL printed on the server, "
                                "including ?token=... (see console_bridge stdout).",
                           content_type="text/plain")
                return
            self._serve_app()
            return
        if u.path in ROUTES_GET:
            if not self._token_ok_header():
                self._send(403, {"error": "missing/invalid X-Console-Token"})
                return
            try:
                code, obj = ROUTES_GET[u.path](parse_qs(u.query))
            except Exception as e:  # noqa: BLE001 -- surface as JSON, never 500-crash the thread
                code, obj = 500, {"error": type(e).__name__, "detail": str(e)}
            self._send(code, obj)
            return
        self._send(404, {"error": "not found"})

    def do_POST(self):
        u = urlparse(self.path)
        if u.path not in ROUTES_POST:
            self._send(404, {"error": "not found"})
            return
        if not self._token_ok_header():
            self._send(403, {"error": "missing/invalid X-Console-Token"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            body = json.loads(self.rfile.read(length) or "{}")
        except (ValueError, json.JSONDecodeError):
            self._send(400, {"error": "body must be JSON"})
            return
        try:
            code, obj = ROUTES_POST[u.path](body)
        except Exception as e:  # noqa: BLE001
            code, obj = 500, {"error": type(e).__name__, "detail": str(e)}
        self._send(code, obj)

    def _serve_app(self):
        if not SERVED_HTML.exists():
            self._send(500, f"served UI not built -- run: python3 ui/build_console.py --served\n"
                            f"(expected {SERVED_HTML})", content_type="text/plain")
            return
        html = SERVED_HTML.read_text()
        # Inject the bridge base + token so the page's API client can call back.
        inject = (f'<script>window.__BRIDGE__={{base:"",token:{json.dumps(TOKEN)}}};</script>')
        html = html.replace("<!--@@BRIDGE_INJECT@@-->", inject)
        self._send(200, html, content_type="text/html; charset=utf-8")


def main() -> int:
    global TOKEN, PORT
    ap = argparse.ArgumentParser(description="Capture Console bridge (localhost only)")
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--token", type=str, default=None,
                    help="fixed token (default: a fresh random one each start)")
    a = ap.parse_args()

    (RUNS / ".staging").mkdir(parents=True, exist_ok=True)
    TOKEN = a.token or secrets.token_urlsafe(24)
    PORT = a.port

    if not SUBSET_RUN.exists():
        sys.exit(f"subset_run.py not found at {SUBSET_RUN}")
    if not SERVED_HTML.exists():
        print(f"[bridge] WARNING: served UI missing -- run: python3 ui/build_console.py --served")

    server = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    url = f"http://localhost:{PORT}/?token={TOKEN}"
    print("=" * 70)
    print("  Capture Console bridge -- LOCALHOST ONLY (127.0.0.1)")
    print(f"  From your laptop:  ssh -L {PORT}:localhost:{PORT} <user>@<this-server>")
    print(f"  Then open:         {url}")
    print("  Keep this token private; anyone with it can launch captures as you.")
    print("=" * 70)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[bridge] shutting down")
        server.shutdown()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
