#!/usr/bin/env python3
"""Plan 07 -- NEW-FAMILIES capture steps (benign system-behaviour benchmarks).

Captures the next-generation benign workloads added to VM_executables_phase2 --
the CPU, CACHE, MEM (+2), IO, THREAD, and MIXED families -- so the corpus grows
past 5 families and the leave-one-family-out significance floor falls below 0.05.

ALL of these are benign benchmarks: no network, no persistence, file I/O confined
to the scratch dir under /var/tmp (see VM_executables_phase2/docs/SAFETY_MODEL.md).
Build + smoke-test them on the guest FIRST (`make && bash scripts/smoke_all.sh`)
before launching a real capture -- do not capture un-smoke-tested binaries.

    python3 plan07_campaign/generate_newfamilies_steps.py
      -> plan07_campaign/newfamilies_steps.txt     (32 cells = 16 workloads x 1 dur x 2 reps)
      -> plan07_campaign/newfamilies_manifest.csv

Flags / BIN / scratch mirror generate_repfill_steps.py. The IDLE shell scripts
(idle_long_baseline.sh / idle_post_workload_recovery.sh) are captured separately,
like run_idle, and are not part of this binary-only step file.
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

BIN = "/home/kali/memorySignal/VM_executables_phase2/bin"
SCRATCH = "/var/tmp/wl_campaign"      # real disk, NOT RAM-backed /tmp (avoids the fill + APF contamination)

# (binary, flags, scratch-dir flag | None). File-touching IO/MIXED workloads
# write their backing file under SCRATCH via --backing-dir; the rest are pure
# memory/CPU and need no scratch.
WORKLOADS = [
    # CPU family
    ("cpu_hash_loop_v2",            "--block-kb 4",                              None),
    ("cpu_matrix_mult_v2",          "--dim 512",                                 None),
    ("cpu_branch_random_v2",        "--table-kb 64",                             None),
    # CACHE family
    ("cache_hot_loop_v2",           "--buffer-kb 32",                            None),
    ("cache_cold_scan_v2",          "--working-set-mb 2048 --mode rmw",          None),
    ("cache_stride_sweep_v2",       "--working-set-mb 2048 --stride 1048576",    None),
    # MEM family (new additions)
    ("mem_random_write_pages_v2",   "--working-set-mb 1024 --bytes-per-page 64", None),
    ("mem_stride_sweep_large_v2",   "--working-set-mb 4096 --stride 1048576",    None),
    # IO family
    ("io_read_cache_hit_v2",        "--file-size-mb 512 --block-bytes 4096",     "--backing-dir"),
    ("io_direct_write_like_v2",     "--file-size-mb 512 --mode rand --block-bytes 4096", "--backing-dir"),
    # THREAD family
    ("thread_lock_contention_v2",   "",                                          None),
    ("thread_producer_consumer_v2", "--ring-size 1024",                          None),
    ("thread_parallel_alloc_v2",    "--min-kb 1 --max-kb 256",                   None),
    # MIXED family
    ("mixed_mem_io_v2",             "--working-set-mb 512 --file-size-mb 256",   "--backing-dir"),
    ("mixed_cpu_mem_v2",            "--working-set-mb 512",                      None),
    ("mixed_cpu_io_v2",             "--file-size-mb 256",                        "--backing-dir"),
]
DURATIONS = [300]          # one fixed length, matching the go-forward design
REPS = [1, 2]              # two replicates (these are brand-new workloads -> fresh cell_ids)

HERE = Path(__file__).resolve().parent


def safe_label(binary: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", binary).strip("._-") or "step"


def main() -> int:
    steps: list[str] = []
    rows: list[dict] = []
    i = 0
    for rep in REPS:
        for dur in DURATIONS:
            for binary, flags, scratch_flag in WORKLOADS:
                i += 1
                scratch = f" {scratch_flag} {SCRATCH}" if scratch_flag else ""
                flagstr = f" {flags}" if flags else ""
                cmd = f"{BIN}/{binary}{flagstr}{scratch} --duration {dur} --phase-markers"
                steps.append(cmd)
                test_name = f"test{i}_{safe_label(binary)}"
                rows.append({"step_index": i, "test_name": test_name, "workload": binary,
                             "duration_s": dur, "rep": rep,
                             "traj_file": f"run_matrix_{test_name}.npy.apf_trajectory.jsonl"})

    header = (
        "# Plan 07 -- NEW benign system-behaviour families (CPU/CACHE/MEM/IO/THREAD/MIXED).\n"
        "# GENERATED by generate_newfamilies_steps.py -- regenerate, do not hand-edit.\n"
        "# All workloads are benign benchmarks (no network/persistence; file I/O under\n"
        "# /var/tmp). BUILD + SMOKE on the guest first: make && bash scripts/smoke_all.sh.\n"
        "# Launch (server, inside screen):\n"
        "#   CAPTURE_MODE=1 CAPTURE_METRIC=apf_queue SUSTAIN_LOOP=1 \\\n"
        "#     SSH_TARGET=kali@192.168.222.63 \\\n"
        "#     SSH_KEY=/project/homes/jeries/.ssh/id_ed25519 \\\n"
        "#     CONFIG=config_qemu_upc.json STEPS_FILE=plan07_campaign/newfamilies_steps.txt \\\n"
        "#     python3 -u run_files_controlled.py 2>&1 | tee plan07_campaign/newfamilies.log\n"
        "# (verify SSH_TARGET / SSH_KEY match your current server before launching.)\n"
    )
    (HERE / "newfamilies_steps.txt").write_text(header + "\n".join(steps) + "\n")
    with (HERE / "newfamilies_manifest.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

    print(f"wrote newfamilies_steps.txt ({len(steps)} steps) + newfamilies_manifest.csv")
    assert len(steps) == 32, f"expected 32 cells, got {len(steps)}"
    print("cells: 32 (16 workloads x 1 duration x 2 reps) OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
