#!/usr/bin/env python3
"""Plan 07 -- fixed-length REPLICATE-FILL steps (safe unattended capture).

Captures the SAME 11 workloads already deployed on the guest, at ONE fixed length
(300 s), for two more replicates (rep 3 and 4). This is the plan's "repetitions at
the fixed length" step: it adds within-workload variance for the bootstrap CIs, on
known-good, already-deployed binaries -- safe to launch and walk away.

It does NOT add new workloads/families (those need build+deploy on the guest first,
done with a smoke test, not blind). Workload flags / BIN / scratch are copied
VERBATIM from plan05_campaign/generate_full_steps.py -- do not diverge.

    python3 plan07_campaign/generate_repfill_steps.py
      -> plan07_campaign/repfill_steps.txt   (22 cells = 11 workloads x 1 dur x 2 reps)
      -> plan07_campaign/repfill_manifest.csv

cell_id = sha1(workload|interval_ms|duration_s|replicate); rep 3/4 => distinct from
the existing rep 1/2 cells, so this APPENDS to the corpus (no collision).
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

BIN = "/home/kali/memorySignal/VM_executables_phase2/bin"
SCRATCH = "/var/tmp/wl_campaign"      # real disk, NOT the RAM-backed /tmp (avoids the fill)

WORKLOADS = [
    ("sandbox_ransom_seq",        "--files 4000 --file-size-bytes 1048576",  "--sandbox-dir"),
    ("sandbox_ransom_slowburn",   "--files 200 --interval-s 3",              "--sandbox-dir"),
    ("sandbox_ransom_selective",  "--files 1500 --file-size-bytes 1048576",  "--sandbox-dir"),
    ("sandbox_ransom_batched",    "--files 5000 --file-size-bytes 1048576",  "--sandbox-dir"),
    ("sandbox_scanner_metadata",  "--files 5000 --subdirs 50 --passes 40",   "--sandbox-dir"),
    ("mem_workingset_sweep_v2",   "--working-set-mb 256 --stride 4096",       None),
    ("mem_mmap_traversal_v2",     "--variant rmw --file-size-mb 256",         "--backing-dir"),
    ("mem_pagefault_density_v2",  "--variant mixed --working-set-mb 256",     None),
    ("mem_rmw_intensity_v2",      "--mode rmw --working-set-mb 256 --stride 4096", None),
    ("mem_writemag_sweep_v2",     "--working-set-mb 256 --bytes-per-page 64", None),
    ("app_hashtable_intensive_v2","--capacity-pow2 24 --inserts 6000000 --lookups 10000000", None),
]
DURATIONS = [300]          # one fixed length
REPS = [3, 4]              # two new replicates (existing data is rep 1, 2)

HERE = Path(__file__).resolve().parent


def safe_label(binary: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", binary).strip("._-") or "step"


def main() -> int:
    steps: list[str] = []
    rows: list[dict] = []
    i = 0
    for rep in REPS:
        for dur in DURATIONS:
            for binary, flags, scratch_flag in WORKLOADS:
                i += 1
                scratch = f" {scratch_flag} {SCRATCH}" if scratch_flag else ""
                cmd = f"{BIN}/{binary} {flags}{scratch} --duration {dur} --phase-markers"
                steps.append(cmd)
                test_name = f"test{i}_{safe_label(binary)}"
                rows.append({"step_index": i, "test_name": test_name, "workload": binary,
                             "duration_s": dur, "rep": rep,
                             "traj_file": f"run_matrix_{test_name}.npy.apf_trajectory.jsonl"})

    header = (
        "# Plan 07 -- fixed-length REPLICATE-FILL (existing 11 workloads, 300s, reps 3+4).\n"
        "# GENERATED by generate_repfill_steps.py -- regenerate, do not hand-edit.\n"
        "# Safe unattended capture: known-good deployed binaries; SUSTAIN_LOOP re-runs\n"
        "# each line until --duration elapses. The manifest gives rep 3/4 so cell_ids\n"
        "# are distinct from the existing rep 1/2 cells. Launch (server, inside screen):\n"
        "#   CAPTURE_MODE=1 CAPTURE_METRIC=apf_queue SUSTAIN_LOOP=1 \\\n"
        "#     SSH_TARGET=kali@192.168.222.63 \\\n"
        "#     SSH_KEY=/project/homes/jeries/.ssh/id_ed25519 \\\n"
        "#     CONFIG=config_qemu_upc.json STEPS_FILE=plan07_campaign/repfill_steps.txt \\\n"
        "#     python3 -u run_files_controlled.py 2>&1 | tee plan07_campaign/repfill.log\n"
        "# (verify SSH_TARGET / SSH_KEY match your current server before launching.)\n"
    )
    (HERE / "repfill_steps.txt").write_text(header + "\n".join(steps) + "\n")
    with (HERE / "repfill_manifest.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

    print(f"wrote repfill_steps.txt ({len(steps)} steps) + repfill_manifest.csv")
    assert len(steps) == 22, f"expected 22 cells, got {len(steps)}"
    print("cells: 22 (11 workloads x 1 duration x 2 reps) OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
